# Generated by Django 2.2 on 2020-06-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
