# Generated by Django 2.2 on 2020-09-19 10:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='Phone',
        ),
        migrations.AddField(
            model_name='billing',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
